spring.application.name=RealEstate

spring.application.name=RealEstate
spring.datasource.url=jdbc:sqlserver://DESKTOP-43HIK1B;databaseName=DapperRealEstateDB;integratedSecurity=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.type-aliases-package=tr.com.huseyinaydin.dto
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.tr.com.huseyinaydin=DEBUG
